[HECATE]
app_name = payment-service
discovery_url = http://127.0.0.1:8771
port = 8772

[RESOURCES]
# Control the number of CPU cores and RAM allocated to the application.
# If not specified, the system will automatically determine available resources. 
cpu_count = 8
ram_total_mb = 1024

# Optional: Specify a custom CPU core assignment mask (e.g., 1:1:6) to control which CPU cores the application can use.
cpu_assignment = 1:1:6